name = "evm-abi-benchmarks"
defaultTargets = ["bench"]

[[lean_exe]]
name = "bench"
root = "Bench"

[[require]]
name = "abi-lean"
git = "https://github.com/yihuang/evm-abi-lean.git"
rev = "69b3f96b58eeb1a06a077ee2193d3cc48d5038bb"
