name = "evm-abi-benchmarks"
defaultTargets = ["bench"]

[[lean_exe]]
name = "bench"
root = "Bench"

[[require]]
name = "abi-lean"
git = "https://github.com/yihuang/evm-abi-lean.git"
rev = "689884beda259b4ebbf3604649eee98a507750e5"
